/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-1",
  aws_appsync_graphqlEndpoint:
    "https://2glzvba7x5axdnyryllxemugwa.appsync-api.us-east-1.amazonaws.com/graphql",
  aws_appsync_region: "us-east-1",
  aws_appsync_authenticationType: "API_KEY",
  aws_appsync_apiKey: "da2-itqqhcwivvhlfjbqj5ort6iqlm",
  aws_cognito_identity_pool_id:
    "us-east-1:abbcb69b-cef4-4cc5-b08d-2512e91e11a8",
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: "us-east-1_OpLOAtOiH",
  aws_user_pools_web_client_id: "13vfc42b0kdh9b4esnojebdsdf",
  oauth: {},
  aws_cognito_username_attributes: [],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ["EMAIL"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
  aws_dynamodb_all_tables_region: "us-east-1",
  aws_dynamodb_table_schemas: [
    {
      tableName: "dynamoAlbums-dev",
      region: "us-east-1",
    },
  ],
};

export default awsmobile;
